### PR TITLE
Improve monorepo deploy

### PR DESCRIPTION
**Pull request by vapaj**
Improves #290

Changes:
- commits build trigger files automatically
- builds spago projects before calculating trigger hashes (because it's important to have up to date hashes, otherwise they would always change). The downside to this is that pre-commits would take a lot of time, which is why...
- uses `pre-push` hook instead of `pre-commit` hook, because we don't need to create trigger files that often really

Let's see if this makes developing affresco any less annoying (it should) 💩

### CODE REVIEW

**Comment by vapaj** [comment]
This is not that urgent PR, so @ae-mo, let's go through this when the holidays are over 🙂

**Comment by f-f** [comment]
Maybe I'm missing something, but what's the reason why we need to have the hash files?

**Comment by vapaj** [comment]
> Maybe I'm missing something, but what's the reason why we need to have the hash files?

@f-f It's because of the Netlify monorepo deploys: Netlify only deploys apps when there changes under a configured app directory, which is neat. However, this gets tricky with our purescript apps, as the changes are mostly made outside of the app directory. To tackle this, we have these deploy trigger files inside the app directories, which simply are the sha256 hashes of the content of the complied purescript of the `/output` dir.

What initially sounded a like simple thing, is becoming a perl monster.

**Comment by f-f** [comment]
Yeah I had that feeling.

I think there are two most sensible paths here:
1. just redeploy everything when anything changes. Questions about that:
  - is it even possible to configure Netlify to do it?
  - if yes, is that too slow or using too many CI minutes?
2. use a smarter (and most importantly already implemented) build system to do this - would Make work here if we use it to run all the deployments? I think it should be able to pickup changes if we define targets properly?

**Comment by vapaj** [comment]
> is it even possible to configure Netlify to do it?

Yes, it was initially like this

> if yes, is that too slow or using too many CI minutes?

It's super slow and often hangs/cancels deployments because of too many concurrent jobs (also doesn't make sense to upgrade our plan just for this)

> would Make work here

Possibly. Do you have any concrete ideas on this?

**Comment by vapaj** [comment]
Does @mrskug have any ideas?

Basically every solution not adding stuff to git would be preferable.

**Comment by ae-mo** [comment]
Sorry guys I completely missed that I was appointed as reviewer 😅

**Comment by f-f** [comment]
@ae-mo I think this is going to be replaced by #404?

**Pull request closed without merging**
