### PR TITLE
Add IconAction component

### PR DESCRIPTION
**Pull request by vapaj**
Adds `IconAction` component. We are using the same style of `<icon> <description>` links/actions in a couple of places in mitt konto (and underlying components) so this will make it a bit nicer. This also makes a clear distinction of css classes and module responsibilities regarding these actions.

### CODE REVIEW

**Comment by ae-mo** [comment]
This might be a good occasion to do a bigger refactoring: move `Subscription`, `TemporaryAddressChange`, `PauseSubscription` and `DeliveryReclamation` in the `mitt-konto` app. 
Moreover, the `ActionsWrapper` was created with the intention of using it for the subscription update actions as well, so this is probably a good moment to do this too.

**Comment by vapaj** [comment]
> I mean, a different PR could do it too

Sounds like a few PRs already! 😄 As a note, I'm fine having these components under `packages/components` even though they aren't used, and probably will not ever be used, outside of `apps/mitt-konto`. However, these components do not have any dependencies (at least the shouldn't) for mitt konto currently, like css classes. So in that way, they are simple "stand-alone" components. What is your motivation to move them under mitt konto?

**Comment by ae-mo** [comment]
> What is your motivation to move them under mitt konto?

They are there for modularizing the **mitt-konto** interface, they are not going to be reused anywhere else, unless a big twist happens. They were developed specifically to be displayed in **mitt-konto**, thus they are effectively part of it.

**Comment by vapaj** [comment]
I don't disagree with you, I'm just fine separating them under `components` 😃 Having them under `mitt-konto` would probably make things clearer though.

However, if we do this, then I suggest we move everything only used by mitt konto under `mitt-konto` to be consistent. Also in that scenario I'd like the css classes to be renamed and possibly moved into `mitt-konto.less` (in any case, having the `<ComponentName>.less` doesn't fit well anymore).

**Comment by vapaj** [comment]
To be fair, vetrina is structured like this and it wouldn't make sense to separate `Vetrina.Products` under `components`.

**Comment by ae-mo** [comment]
> However, if we do this, then I suggest we move everything only used by mitt konto under mitt-konto to be consistent. Also in that scenario I'd like the css classes to be renamed and possibly moved into mitt-konto.less (in any case, having the <ComponentName>.less convention doesn't fit well anymore).

I agree. I guess I'll make an umbrella issue for this migration.

**Review by ae-mo — APPROVED** [review]

**Pull request merged**
